const assert=require('node:assert/strict');
const DraftStore=require('../roleweaver/static/drafts.js');
const map=new Map();const storage={getItem:k=>map.get(k),setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};
const a=new DraftStore(storage,'world_a');const base={name:'Saved'};const v={name:'Draft'};
a.write('profile:mira',v,base);
assert.deepEqual(new DraftStore(storage,'world_a').read('profile:mira').values,v);
assert.equal(new DraftStore(storage,'world_b').read('profile:mira'),null);
assert.equal(a.read('profile:orren'),null);
a.write('profile:mira',{name:'Newer edits'},base);a.saved('profile:mira',v);
assert.equal(a.read('profile:mira').values.name,'Newer edits');
a.saved('profile:mira',{name:'Newer edits'});assert.equal(a.read('profile:mira'),null);
a.write('world',v,base);a.write('world',base,base);assert.equal(a.read('world'),null);
a.write('memory:mira',v,base);a.remove('memory:mira');assert.equal(a.read('memory:mira'),null);
map.set(a.prefix+'broken','{');assert.throws(()=>a.read('broken'));
const broken=new DraftStore({setItem(){throw Error('Storage full')}},'world');assert.throws(()=>broken.write('x',v,base));
console.log('Draft recovery tests passed');
const fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync(require('node:path').join(__dirname,'../roleweaver/static/index.html'),'utf8');
const elements={};function element(){return {value:'',disabled:false,maxLength:80,textContent:'',children:[],replaceChildren(){this.children=[]},append(...x){this.children.push(...x)},querySelector(){return this.button??=element()},setCustomValidity(){}}}
const context=vm.createContext({DraftStore,local:storage,creating:false,$:id=>elements[id]??=element(),document:{createElement:element,createTextNode:x=>x}});
vm.runInContext(html.slice(html.indexOf('let draftStore=null;'),html.indexOf('fields.forEach(id=>')),context);
vm.runInContext("draftStore=new DraftStore(local,'ui');$('name').value='Server';draftStore.write('profile:mira',{name:'Recovered'},{name:'Old server'});mountDraft('profile','profile:mira',['name'],'profile')",context);
assert.equal(elements.name.value,'Server');assert.equal(elements.name.disabled,true);
assert.match(elements['draft-profile'].children[0].textContent,/Saved data has changed/);
elements['draft-profile'].children[1].onclick();assert.equal(elements.name.value,'Recovered');assert.equal(elements.name.disabled,false);
vm.runInContext("$('name').value='Server';mountDraft('profile','profile:mira',['name'],'profile')",context);
elements['draft-profile'].children[3].onclick();assert.equal(elements.name.value,'Server');assert.equal(elements.name.disabled,false);
assert.equal(new DraftStore(storage,'ui').read('profile:mira'),null);
console.log('Draft UI checks passed: explicit recovery, conflict warning and discard.');
