#!/usr/bin/env python3
"""Maintainer-only cleanup of a freshly provisioned, disposable build VM.

Never point this at the private testing VM. The explicit build marker must be
created when a new image is assembled; normal launchers never create it.
"""

import json
import os
from pathlib import Path
import shutil
import socket
import subprocess


def run(*args):
    subprocess.run(args, check=True)


def main():
    marker = Path("/root/roleweaver-disposable-build")
    if (
        os.geteuid() != 0
        or socket.gethostname() != "roleweaver-demo"
        or not marker.is_file()
        or marker.read_text().strip() != "fresh-public-image-no-player-data"
    ):
        raise RuntimeError("This is not an explicitly marked disposable image build")
    home = Path("/home/roleweaver")
    world = home / "demo/.demo/qemu_demo"
    if world.resolve() != world or not (world / "settings.json").is_file():
        raise RuntimeError("Unexpected demo installation path")
    config = json.loads((world / "config.json").read_text())
    if (
        config.get("provider") != "offline"
        or (world / "data/llm-settings.json").exists()
    ):
        raise RuntimeError(
            "Factory image must have no configured provider or saved API settings"
        )
    run("systemctl", "stop", "roleweaver-demo", "roleweaver-dashboard-relay")
    # Flush only this isolated build VM's Redis; never an existing server's Redis.
    run("redis-cli", "FLUSHALL")
    run("redis-cli", "SAVE")
    run("systemctl", "stop", "redis-server")
    # Exact allowlist: fresh runtime data, logs, build inputs and build credentials.
    targets = [
        world / "data",
        world / "backups",
        world / "update-backups",
        world / "firstboot-data",
        home / ".ssh",
        home / ".cache",
        home / ".bash_history",
        home / "native.tar.gz",
        home / "RoleWeaver-Demo-1.0.0.tar.gz",
        home / "install-guest.sh",
        home / "build-install.log",
        Path("/var/lib/cloud"),
        Path("/var/lib/roleweaver"),
        Path("/root/.ssh"),
    ]
    targets += list(world.glob("*.log")) + list(world.glob("*.pid"))
    targets += list(world.glob("dashboard-auth*"))
    for name in ("logs", "servervault", "localvault", "saves", "temp", "database"):
        targets.append(world / "userdata" / name)
    for target in targets:
        if target.is_symlink():
            target.unlink()
        elif target.is_dir():
            shutil.rmtree(target)
        elif target.exists():
            target.unlink()
    for key in Path("/etc/ssh").glob("ssh_host_*"):
        key.unlink()
    # Default credentials are generated by the application on first run.
    settings = json.loads((world / "settings.json").read_text())
    settings["dm_password"] = "roleweaver"
    (world / "settings.json").write_text(json.dumps(settings, indent=2) + "\n")
    Path("/etc/cloud/cloud-init.disabled").touch()
    Path("/etc/machine-id").write_text("")
    dbus = Path("/var/lib/dbus/machine-id")
    if dbus.exists() or dbus.is_symlink():
        dbus.unlink()
    dbus.symlink_to("/etc/machine-id")
    run("apt-get", "clean")
    run("journalctl", "--rotate")
    run("journalctl", "--vacuum-time=1s")
    for name in (
        "auth.log",
        "cloud-init.log",
        "cloud-init-output.log",
        "wtmp",
        "btmp",
        "lastlog",
    ):
        path = Path("/var/log") / name
        if path.exists():
            path.write_bytes(b"")
    marker.unlink()
    run("sync")
    run("fstrim", "-av")
    print("Factory image sealed. Power off; flatten the disk before distribution.")


if __name__ == "__main__":
    main()
