// Generated by prepare_dialogues.py. Keep the original condition installed.
#include "rw_tr_nodes"
int StartingConditional()
{
 RWTrNodeRestore(2000011);
 RWTrNodeVisible("rw_tr_demo", "dialogue_reply", 1, 2000011);
 return TRUE;
}
