// Generated by prepare_dialogues.py. Keep the original condition installed.
#include "rw_tr_nodes"
int StartingConditional()
{
 RWTrNodeRestore(2000020);
 RWTrNodeVisible("rw_tr_demo", "dialogue_reply", 10, 2000020);
 return TRUE;
}
