// Generated by prepare_dialogues.py. Keep the original condition installed.
#include "rw_tr_nodes"
int StartingConditional()
{
 RWTrNodeRestore(2000007);
 RWTrNodeVisible("rw_tr_demo", "dialogue_entry", 7, 2000007);
 return TRUE;
}
