// Generated by prepare_dialogues.py. Keep the original condition installed.
#include "rw_tr_nodes"
int StartingConditional()
{
 RWTrNodeRestore(2000018);
 RWTrNodeVisible("rw_tr_demo", "dialogue_reply", 8, 2000018);
 return TRUE;
}
