// Generated by prepare_dialogues.py. Keep the original condition installed.
#include "rw_tr_nodes"
int StartingConditional()
{
 RWTrNodeRestore(2000004);
 RWTrNodeVisible("rw_tr_demo", "dialogue_reply", 0, 2000004);
 return TRUE;
}
