// Generated by prepare_dialogues.py. Keep the original condition installed.
#include "rw_tr_nodes"
int StartingConditional()
{
 RWTrNodeRestore(2000000);
 RWTrNodeVisible("rw_tr_demo", "dialogue_entry", 0, 2000000);
 return TRUE;
}
