// Generated by prepare_dialogues.py. Keep the original condition installed.
#include "rw_tr_nodes"
int StartingConditional()
{
 RWTrNodeRestore(2000017);
 RWTrNodeVisible("rw_tr_demo", "dialogue_reply", 7, 2000017);
 return TRUE;
}
