// Generated by prepare_dialogues.py. Keep the original condition installed.
#include "rw_tr_nodes"
int StartingConditional()
{
 RWTrNodeRestore(2000016);
 RWTrNodeVisible("rw_tr_demo", "dialogue_reply", 6, 2000016);
 return TRUE;
}
