// Generated by prepare_dialogues.py. Keep the original condition installed.
#include "rw_tr_nodes"
int StartingConditional()
{
 RWTrNodeRestore(2000006);
 RWTrNodeVisible("rw_tr_demo", "dialogue_entry", 6, 2000006);
 return TRUE;
}
