// Generated by prepare_dialogues.py. Keep the original condition installed.
#include "rw_tr_nodes"
int StartingConditional()
{
 RWTrNodeRestore(2000015);
 RWTrNodeVisible("rw_tr_demo", "dialogue_reply", 5, 2000015);
 return TRUE;
}
