// Generated by prepare_dialogues.py. Keep the original condition installed.
#include "rw_tr_nodes"
int StartingConditional()
{
 RWTrNodeRestore(2000012);
 RWTrNodeVisible("rw_tr_demo", "dialogue_reply", 2, 2000012);
 return TRUE;
}
