"""Generate the optional native dialogue fixture from editable English source.

Run from the repository root: python tools/build_translation_demo.py
Produces the dialogue, an ordinary Royal Guide, wrappers and the text manifest.
No live files change.
Private per-player tokens fill standard NWN dialogue nodes; no shared text mutation.
"""

import json
import sys
import copy
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from tools.gff import read, write, text
from tools.prepare_dialogues import prepare_dialogue


def build_creature(base):
    """A normal module NPC with a DLG, not an AI profile or persistent placement."""
    signature, creature = read(base)
    fields = copy.deepcopy(creature[1])
    for key, (kind, value) in list(fields.items()):
        if key.startswith("Script"):
            fields[key] = (kind, b"")
    fields.update(
        TemplateResRef=(11, b"rw_tr_guide"),
        Tag=(10, b"rw_tr_guide"),
        FirstName=(12, text("Royal Guide")),
        LastName=(12, text("")),
        Description=(
            12,
            text(
                "Speak to this guide to test a standard NPC dialogue and its translated replies. Use /rw language to choose your reading language."
            ),
        ),
        Conversation=(11, b"rw_tr_demo"),
        ScriptDialogue=(11, b"rw_tr_talk"),
        FactionID=(2, 2),
        Plot=(0, 1),
        IsImmortal=(0, 1),
        VarTable=(15, []),
        ItemList=(15, []),
        Equip_ItemList=(15, []),
        ClassList=(15, [(2, {"Class": (5, 20), "ClassLevel": (3, 1)})]),
    )
    return write(signature, (creature[0], fields))


def build(source, prepared=True):
    nodes = source["nodes"]
    assert [n["id"] for n in nodes] == list(range(len(nodes)))
    assert 0 < len(nodes) <= 32
    groups = {
        kind: [n for n in nodes if n["kind"] == kind]
        for kind in ("dialogue_entry", "dialogue_reply")
    }
    indices = {n["id"]: i for group in groups.values() for i, n in enumerate(group)}

    def node(fields, tag=0):
        return tag, dict(fields)

    def link(i, child=False):
        return node(
            {"Active": (11, b""), "Index": (4, indices[i]), "IsChild": (0, int(child))}
        )

    def entry(n):
        entry_node = n["kind"] == "dialogue_entry"
        assert all(nodes[i]["kind"] != n["kind"] for i in n["links"])
        fields = {
            "Text": (12, text(n["text"])),
            "Script": (11, b""),
            "Quest": (10, b""),
            "QuestEntry": (4, 0),
            "Comment": (10, n["text"].encode("utf-8")),
            # Required on replies as well as entries. Without it NWN can load
            # a one-liner but rejects the complete dialogue in BeginConversation.
            "Delay": (4, 0xFFFFFFFF),
        }
        fields["RepliesList" if entry_node else "EntriesList"] = (
            15,
            [link(i, i == 0 or (i == 7 and n["id"] != 0)) for i in n["links"]],
        )
        if entry_node:
            fields.update(
                Speaker=(10, b""),
                Sound=(11, b""),
                Animation=(4, 0),
                AnimLoop=(0, 0),
            )
        return node(fields)

    root = node(
        {
            "EntryList": (15, [entry(n) for n in groups["dialogue_entry"]]),
            "ReplyList": (15, [entry(n) for n in groups["dialogue_reply"]]),
            "StartingList": (15, [link(0)]),
            "DelayEntry": (4, 0),
            "DelayReply": (4, 0),
            "EndConversation": (11, b"rw_tr_end"),
            "EndConverAbort": (11, b"rw_tr_end"),
            "NumWords": (4, sum(len(n["text"].split()) for n in nodes)),
            "PreventZoomIn": (0, 1),
        },
        0xFFFFFFFF,
    )
    records = [
        dict(id=n["id"], kind=n["kind"], text=n["text"], approved=1) for n in nodes
    ]
    script = "// Generated by tools/build_translation_demo.py; edit examples/translation_dialogue.json.\n"
    script += 'const string RW_TR_DEMO_RESREF = "' + source["resource"] + '";\n'
    script += "const int RW_TR_DEMO_BASE = " + str(source["token_base"]) + ";\n"
    script += (
        "json RWTrDemoTexts()\n{ return JsonParse("
        + json.dumps(json.dumps(records, separators=(",", ":")))
        + "); }\n"
    )
    raw = write(b"DLG V3.2", root)
    if prepared:
        raw = prepare_dialogue(source["resource"], raw, source["token_base"])[0]
    return raw, script


if __name__ == "__main__":
    source = json.loads(
        (ROOT / "examples/translation_dialogue.json").read_text(encoding="utf-8")
    )
    dlg, script = build(source)
    (ROOT / "assets/rw_tr_demo.dlg").write_bytes(dlg)
    (ROOT / "bridge/rw_tr_demo.nss").write_text(script, encoding="utf-8")
    raw, _ = build(source, prepared=False)
    _, wrappers, _ = prepare_dialogue(source["resource"], raw, source["token_base"])
    for name, code in wrappers.items():
        (ROOT / "bridge" / (name + ".nss")).write_text(code, encoding="utf-8")
    (ROOT / "assets/rw_tr_guide.utc").write_bytes(
        build_creature((ROOT / "assets/rw_base.utc").read_bytes())
    )
    print(
        "Generated the English test dialogue, Royal Guide and private-token text manifest."
    )
