"""Prepare ordinary NWN dialogues for translation on demand, entirely offline.

Reads DLGs from a module and optional resource directories; writes a NEW review
bundle. No provider, database, running server or original resource is modified.
The original graph, actions, quests, localization and condition parameters remain
intact. Only incoming condition references are wrapped. NWNX Dialog changes the
display text at runtime; the DLG's authored text is never replaced with a token.
"""

import argparse
import copy
import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from tools.gff import read, write
from tools.module_copy import resources

RESREF = re.compile(r"[a-z0-9_]{1,16}")


def literal(value):
    """NSS string syntax is not JSON (notably Unicode escapes)."""
    return (
        '"'
        + value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\r", "")
        .replace("\n", "\\n")
        + '"'
    )


def prepare_dialogue(resource, raw, token_base=3000000):
    """Return (DLG bytes, generated NSS mapping, report). No translation calls.

    Source text is read from the active native dialogue when a condition passes.
    This also supports TLK-backed nodes without copying the talk table into SQLite.
    """
    if not RESREF.fullmatch(resource):
        raise ValueError("Invalid dialogue resource: " + resource)
    signature, root = read(raw)
    if signature != b"DLG V3.2":
        raise ValueError("Expected DLG V3.2")
    fields = copy.deepcopy(root[1])
    if "RWTrVersion" in fields:
        raise ValueError("Already prepared; rebuild from the original dialogue")
    groups = {
        "dialogue_entry": fields["EntryList"][1],
        "dialogue_reply": fields["ReplyList"][1],
    }
    count = sum(len(group) for group in groups.values())
    if count > 10000 or not 100000 <= token_base <= 2147483647 - count:
        raise ValueError("Dialogue/token range exceeds preparation limits")
    # Separate entry/reply namespaces: their native indices can be identical.
    tokens = {
        (kind, i): token_base + n
        for n, (kind, i) in enumerate(
            (kind, i) for kind, nodes in groups.items() for i in range(len(nodes))
        )
    }
    scripts, links = {}, []

    def wrap(link, kind):
        edge = link[1]
        index = edge["Index"][1]
        if not isinstance(index, int) or not 0 <= index < len(groups[kind]):
            raise ValueError("Invalid dialogue link")
        original = edge.get("Active", (11, b""))[1].decode("ascii").lower()
        if original and not RESREF.fullmatch(original):
            raise ValueError("Invalid condition script")
        parameters = []
        for _, param in edge.get("ConditionParams", (15, []))[1]:
            if (
                param.get("Key", (None,))[0] != 10
                or param.get("Value", (None,))[0] != 10
            ):
                raise ValueError("Unsupported condition parameter structure")
            key = param["Key"][1].decode("utf-8")
            if not key or key in parameters:
                raise ValueError("Empty or duplicate condition parameter")
            parameters.append(key)
        identity = json.dumps(
            [resource, kind, index, original, parameters, tokens[kind, index]]
        )
        name = "rtd_" + hashlib.sha256(identity.encode()).hexdigest()[:12]
        lines = [
            "// Generated by prepare_dialogues.py. Keep the original condition installed.",
            '#include "rw_tr_nodes"',
            "int StartingConditional()",
            "{",
            f" RWTrNodeRestore({tokens[kind, index]});",
        ]
        if original:
            lines += [' if (!NWNX_Core_PluginExists("NWNX_Util")) return FALSE;']
            # ExecuteScript has a fresh parameter scope. Forward the original
            # names from this link before executing the existing compiled script.
            lines += [
                f" SetScriptParam({literal(key)}, GetScriptParam({literal(key)}));"
                for key in parameters
            ]
            lines += [
                f" ExecuteScript({literal(original)}, OBJECT_SELF);",
                " int allowed = NWNX_Util_GetScriptReturnValue();",
                " if (!allowed) return allowed;",
            ]
        lines += [
            f" RWTrNodeVisible({literal(resource)}, {literal(kind)}, {index}, {tokens[kind, index]});",
            " return " + ("allowed" if original else "TRUE") + ";",
            "}",
            "",
        ]
        source = "\n".join(lines)
        if name in scripts and scripts[name] != source:
            raise ValueError("Generated script collision")
        scripts[name] = source
        edge["Active"] = (11, name.encode("ascii"))
        links.append(
            dict(
                wrapper=name,
                original=original,
                kind=kind,
                index=index,
                parameters=parameters,
            )
        )

    for link in fields.get("StartingList", (15, []))[1]:
        wrap(link, "dialogue_entry")
    for _, node in groups["dialogue_entry"]:
        for link in node.get("RepliesList", (15, []))[1]:
            wrap(link, "dialogue_reply")
    for _, node in groups["dialogue_reply"]:
        for link in node.get("EntriesList", (15, []))[1]:
            wrap(link, "dialogue_entry")
    fields["RWTrVersion"] = (5, 1)
    fields["RWTrTokenBase"] = (4, token_base)
    fields["RWTrTokenCount"] = (4, count)
    report = dict(
        resource=resource,
        source_sha256=hashlib.sha256(raw).hexdigest(),
        nodes=count,
        token_base=token_base,
        token_count=count,
        conditions=links,
    )
    return write(signature, (root[0], fields)), scripts, report


def prepare(
    module,
    directories,
    output,
    token_base=3000000,
    compiler=None,
    runtime=None,
    includes=None,
    only=(),
):
    output = Path(output).resolve()
    if output.exists():
        raise ValueError(
            "Choose a new output folder; existing bundles are never overwritten"
        )
    module = Path(module).resolve() if module else None
    directories = [Path(d).resolve() for d in directories]
    if any(
        output == d or output in d.parents or d in output.parents for d in directories
    ):
        raise ValueError("Output must be separate from input resource directories")
    entries = (
        {(n.lower(), k): b for n, k, b in resources(module.read_bytes())}
        if module
        else {}
    )
    for directory in directories:
        if not directory.is_dir():
            raise ValueError("Missing resource directory: " + str(directory))
        for path in sorted(directory.iterdir()):
            kind = {".dlg": 2029, ".nss": 2009, ".ncs": 2010}.get(path.suffix.lower())
            if path.is_file() and kind:
                entries[path.stem.lower(), kind] = path.read_bytes()
    dialogues = sorted(
        (n, b) for (n, k), b in entries.items() if k == 2029 and (not only or n in only)
    )
    if not dialogues or (set(only) - {n for n, _ in dialogues}):
        raise ValueError("No matching dialogues found")
    if any((compiler, runtime, includes)) and not all((compiler, runtime, includes)):
        raise ValueError(
            "Compilation requires --compiler, --runtime and --includes (matching NWNX headers plus bridge scripts)"
        )
    built, all_scripts, report, cursor, skipped = {}, {}, [], token_base, []
    generated_names = set()
    # Scan local sources for explicit tokens; dynamically calculated token IDs
    # cannot be detected. The report reserves this range for owner review.
    used_tokens = set()
    for (name, kind), raw in entries.items():
        if kind == 2029:
            fields = read(raw)[1][1]
            if "RWTrVersion" in fields:
                base = fields["RWTrTokenBase"][1]
                used_tokens.update(range(base, base + fields["RWTrTokenCount"][1]))
        if kind in (2009, 2029):
            used_tokens.update(int(v) for v in re.findall(rb"<CUSTOM(\d+)>", raw))
            used_tokens.update(
                int(v) for v in re.findall(rb"SetCustomToken\s*\(\s*(\d+)", raw)
            )
    for name, raw in dialogues:
        if "RWTrVersion" in read(raw)[1][1]:
            skipped.append(
                dict(
                    resource=name,
                    reason="Already prepared; keep its current resources. Rebuild it only from the original.",
                )
            )
            continue
        dlg, scripts, item = prepare_dialogue(name, raw, cursor)
        if used_tokens.intersection(range(cursor, cursor + item["nodes"])):
            raise ValueError(
                "Custom token range collides with existing text/scripts; choose --token-base"
            )
        for script, source in scripts.items():
            if (
                any((script, kind) in entries for kind in (2009, 2010))
                or script in generated_names
            ):
                raise ValueError(
                    "Generated wrapper conflicts with an existing resource: " + script
                )
            generated_names.add(script)
        built[name], all_scripts[name] = dlg, scripts
        report.append(item)
        cursor += item["nodes"]
    if not report:
        raise ValueError(
            "All selected dialogues are already prepared; use their original authoring files"
        )
    output.mkdir(parents=True)
    for folder in ("originals", "scripts", "override"):
        (output / folder).mkdir()
    for name, raw in dialogues:
        if name not in built:
            continue
        (output / "originals" / (name + ".dlg")).write_bytes(raw)
        (output / "override" / (name + ".dlg")).write_bytes(built[name])
        for script, source in all_scripts[name].items():
            path = output / "scripts" / (script + ".nss")
            path.write_text(source, encoding="utf-8")
            if compiler:
                subprocess.run(
                    [str(compiler), "-n", str(runtime), "-i", str(includes), str(path)],
                    check=True,
                    capture_output=True,
                    timeout=30,
                )
                shutil.move(
                    path.with_suffix(".ncs"), output / "override" / (script + ".ncs")
                )
    manifest = dict(
        version=1,
        compiled=bool(compiler),
        token_base=token_base,
        token_end=cursor - 1,
        dialogues=report,
        skipped=skipped,
        llm_requests=0,
        translation_database_written=False,
    )
    (output / "manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )
    (output / "INSTALL.md").write_text(
        "# Prepared dialogue translations\n\n"
        "Preparation made **zero LLM requests** and did not write to the translation database.\n\n"
        "1. Keep your original module and resources. Review manifest.json, including the reserved custom-token range.\n"
        "2. Install the current Role Weaver companion and bridge; enable NWNX Dialog, Util and Player plugins.\n"
        "   For independent multiplayer viewers, also build/install the optional NWNX_RWTranslation adapter (extensions/nwnx_translation/README.md). Without it, native replacement falls back to original text while another player is in the area.\n"
        "3. Compile scripts/ using the same NWN runtime, NWNX headers and world-specific bridge as your server if manifest.compiled is false.\n"
        "4. Stop NWN. Back up any same-named files in its override directory. Copy the contents of this bundle's override/ there, together with compiled wrapper .ncs files. Do not copy originals/. Keep original condition/action scripts installed.\n"
        "5. Start NWN. Speak to an NPC with translation off first, checking its quest conditions and actions, then choose /rw language and repeat.\n\n"
        "Only reached lines and available replies request translation. Close and reopen later on a cache miss. Unvisited branches stay out of the database.\n\n"
        "To update authored text/branches, regenerate from the ORIGINAL resources, compile and replace the prepared copies during maintenance. Never prepare an already prepared copy.\n\n"
        "Rollback: stop NWN, remove only this bundle's generated wrapper files and prepared DLG copies, restore the override files you backed up, then start NWN. The original module was never changed.\n\n"
        "See docs/TRANSLATION.md for supported surfaces and limitations.\n",
        encoding="utf-8",
    )
    return manifest


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--module", type=Path)
    parser.add_argument(
        "--resources",
        action="append",
        default=[],
        type=Path,
        help="Extracted DLG/NSS/NCS folder; later folders override earlier inputs",
    )
    parser.add_argument(
        "--dialogue",
        action="append",
        default=[],
        help="Optional resource name to prepare; otherwise all supplied DLGs",
    )
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--token-base", type=int, default=3000000)
    parser.add_argument("--compiler", type=Path)
    parser.add_argument("--runtime", type=Path)
    parser.add_argument(
        "--includes",
        help="Semicolon-separated matching NWNX headers and prepared world bridge directories",
    )
    args = parser.parse_args()
    report = prepare(
        args.module,
        args.resources,
        args.output,
        args.token_base,
        args.compiler,
        args.runtime,
        args.includes,
        args.dialogue,
    )
    print(
        f"Prepared {len(report['dialogues'])} dialogues in {args.output}. Zero LLM calls; no translation database or original files changed."
    )


if __name__ == "__main__":
    try:
        main()
    except (ValueError, OSError, subprocess.SubprocessError) as exc:
        print("Dialogue preparation stopped:", exc, file=sys.stderr)
        if isinstance(exc, subprocess.CalledProcessError):
            print((exc.stdout or b"").decode(errors="replace"), file=sys.stderr)
        raise SystemExit(1)
